#! /bin/sh

if test "$1" = ""; then
  echo "usage: $0 number"
  exit 1
fi

for i in $(seq $1); do
  cat /proc/sys/kernel/random/uuid > file.txt
  git add file.txt
  git commit -m "Commit number $i made at $(date)."
done
